# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d0abee5be16a32d84dba514114288be81d3efa14442a01c0b51297ddf10557840648a80805ac8d32157323154dda49e1bb89171f5d5310b1070e45f95f36383

test:
  secret_key_base: b66ae6d6f9323e976d280aceb9b7afe8ec22da38d8983235e38b082d396ea5f0749327e267648bf05a9e989a7e2e8f0d7abe11e0915a9d5f074681b450f917d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
